INSERT INTO Vasarlas VALUES
(1,CURRENT_TIMESTAMP, 't14',1,'v06');
INSERT INTO Vasarlas VALUES
(2,CURRENT_TIMESTAMP, 't15',1,'v06');
INSERT INTO Vasarlas VALUES
(4,CURRENT_TIMESTAMP, 't03',4,'v01');
INSERT INTO Vasarlas VALUES
(5,CURRENT_TIMESTAMP, 't04',1,'v01');
INSERT INTO Vasarlas VALUES
(6,CURRENT_TIMESTAMP, 't02',2,'v02');
INSERT INTO Vasarlas VALUES
(7,CURRENT_TIMESTAMP, 't06',2,'v02');
INSERT INTO Vasarlas VALUES
(8,CURRENT_TIMESTAMP, 't07',4,'v02');
INSERT INTO Vasarlas VALUES
(11,CURRENT_TIMESTAMP, 't11',3,'v04');
INSERT INTO Vasarlas VALUES
(13,CURRENT_TIMESTAMP, 't13',100,'v05');